-- CREATE DATABASE eventapp;
--
-- CREATE TABLE event (
--     id SERIAL NOT NULL,
--     event_name CHAR(32) NOT NULL,
--     candidate_dates TEXT NOT NULL,
--     deadline CHAR(32) NOT NULL,
--     comment CHAR(256) NOT NULL,
--     planner CHAR(32) NOT NULL,
--     status BOOLEAN DEFAULT FALSE,
--     PRIMARY KEY(id)
-- );
--
-- CREATE TABLE vote (
--     id INT NOT NULL,
--     participant_name CHAR(32) NOT NULL,
--     voting_date CHAR(32) NOT NULL,
--     voting_status INT NOT NULL,
--     PRIMARY KEY(id, participant_name, voting_date)
-- );
--
--
